name = "cf-b2b-website"
main = "src/index.js"
compatibility_date = "2025-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "b2b_database"
database_id = "5b1d67a1-1102-48bc-86f8-0dbd9c355446"

# Environment variables
[vars]
ENVIRONMENT = "development"

# R2 Storage for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "b2b-product-images"

[[kv_namespaces]]
binding = "STATIC_ASSETS" #
id = "6f41ad6a309f4ac2aa6527224d4bb6fa" # 从 Cloudflare 获取的 KV Namespace ID
